---
title: "Figures - Boston dataset examples"
author: "Pablo Morala"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

####################################
# 1 - Load all needed packages and functions
####################################
library(nn2poly)
library(nn2poly.tools)
library(keras)
library(tensorflow)
library(cowplot)
library(ggplot2)


my_seed <- 42
set.seed(my_seed)
tensorflow::tf$random$set_seed(my_seed) # Needed to have reproducible results with keras
```


In this Rmd file we are going to show how to use NN2Poly in X different situations with synthetically generated data.


# Data Loading:

```{r}
boston_housing <- dataset_boston_housing()

c(train_x, train_y) %<-% boston_housing$train
c(test_x, test_y) %<-% boston_housing$test
```


```{r}
# Join the predictor variables (x) and the response (y)
train <- as.data.frame(train_x)
train$Y <- matrix(train_y, ncol = 1)

test <- as.data.frame(test_x)
test$Y <- matrix(test_y, ncol = 1)

# Use the train data to obtain the scaling parameters, then apply them both to 
# test and train
maxs <- apply(train, 2, max)
mins <- apply(train, 2, min) 

train <- as.data.frame(scale(train, 
                             center = mins + (maxs - mins) / 2, 
                             scale = (maxs - mins) / 2))
test <- as.data.frame(scale(test, 
                             center = mins + (maxs - mins) / 2, 
                             scale = (maxs - mins) / 2))

# Divide again in x and y
train_x <- as.matrix(subset(train, select = -c(Y)))
train_y <- as.matrix(train$Y)

test_x <- as.matrix(subset(test, select = -c(Y)))
test_y <- as.matrix(test$Y)

# Define the dimension p of the problem:
p <- dim(train_x)[2]

```


# Keras and nn2poly hyperparameters

These parameters will also be held constant over the networks

```{r}
# keras hyperparameters
my_loss <- "mse"
my_metrics <- "mse"
my_optimizer <- optimizer_rmsprop()
my_epochs <- 1000
my_batch <- 200
my_validation_split <- 0.2
my_verbose <- 0

```


```{r}
q_taylor_at_each_layer <- 8 # We can set a high value as we are going
# to limit it with a forced max Q.
forced_max_Q <- 3 # Choose 3 as data generated will be of order 2.
```


# Function to generate the desired graphs:

```{r}
perform_example_from_train_test<- function(train,
                                           test,
                                           af_string_list,
                                           h_neurons_vector,
                                           q_taylor_vector,
                                           forced_max_Q,
                                           my_max_norm,
                                           my_optimizer,
                                           my_loss,
                                           my_metrics,
                                           my_epochs,
                                           my_batch,
                                           my_validation_split,
                                           my_verbose,
                                           all_partitions) {

  # Obtain parameters:
  p <- ncol(train) - 1
  
  # Divide again in x and y
  train_x <- as.matrix(subset(train, select = -c(p+1)))
  train_y <- as.matrix(subset(train, select = c(p+1)))
  
  test_x <- as.matrix(subset(test, select = -c(p+1)))
  test_y <- as.matrix(subset(test, select = c(p+1)))
  
  # Build the nn
  nn <- build_keras_model(
    p,
    af_string_list,
    h_neurons_vector,
    my_max_norm
  )
  
  # Compile the model
  compile(nn,
          loss = my_loss,
          optimizer = my_optimizer,
          metrics = my_metrics
  )
  
  # Fit the model
  history <- fit(nn,
                 train_x,
                 train_y,
                 verbose = my_verbose,
                 epochs = my_epochs,
                 validation_split = my_validation_split,
                 batch_size = my_batch
  )
  plot_history <- plot(history)

  # Obtain the predicted values with the NN to compare them
  prediction_NN <- predict(nn, test_x)
  
  # plot that comparison between NN and original
  plot_NN_performance <- plot_NN_PR_comparison(unname(test_y), prediction_NN)
  
  plot_NN_performance <- plot_NN_performance +
    ggplot2::labs(x = "Original Y") +
    theme_half_open()
  
  # MSE between NN and Poly
  n_test <- length(test_y)
  MSE_NN_vs_original<- sum((prediction_NN - test_y)^2) / n_test
  
  # Extract the weights:
  keras_weights <- keras::get_weights(nn)
  
  n <- length(keras_weights)
  
  if(my_max_norm[[1]]=="no_constraint"){
    
    n2 <- n/2
    
    nn_weights <- vector(mode = "list", length = n2)
    for (i in 1:n2){
      nn_weights[[i]] <- rbind(keras_weights[[2*i]], keras_weights[[2*i-1]])
    }
    
  } else {
    nn_weights <- keras_weights[1:(n - 2)]
    
    nn_weights[[n - 1]] <- rbind(keras_weights[[n]], keras_weights[[n - 1]])
  }
  
  # use the  nn2poly algorithm
  coeffs <- nn2poly::nn2poly_algorithm(
    weights_list = nn_weights,
    af_string_list = af_string_list,
    q_taylor_vector = q_taylor_vector,
    forced_max_Q = forced_max_Q,
    all_partitions = all_partitions,
    store_coeffs = FALSE
  )
  
  labels <- coeffs[[length(coeffs)]][[1]]
  coeffs <- coeffs[[length(coeffs)]][[2]]
  
  # Obtain the predicted values for the test data with our polynomial
  n_test <- length(test_y)
  prediction_poly <- rep(0, n_test)
  
  for (i in 1:n_test) {
    prediction_poly[i] <- nn2poly::eval_poly(test[i, seq(p)], labels = labels, coeffs = coeffs)
  }
    
  # MSE between NN and Poly
  MSE_NN_vs_poly <- sum((prediction_NN - prediction_poly)^2) / n_test
  
  # Plot the PR vs NN predictions
  plot_PR_vs_NN <- plot_NN_PR_comparison(prediction_poly, prediction_NN) +
    theme_half_open()
  
  # Plot the taylor expansion at each layer:
  plot_taylor <- plot_taylor_and_synpatic_potentials(
    data = train,
    weights_list = nn_weights,
    af_string_list = af_string_list,
    q_taylor_vector = q_taylor_vector
  ) 
  
  for (i in 1:length(plot_taylor)){
    plot_taylor[[i]] <- plot_taylor[[i]] + 
      theme_half_open()
  }
  
  output <- vector(mode = "list", length = 0)
  output$MSE_NN_vs_poly <- MSE_NN_vs_poly
  output$MSE_NN_vs_original <- MSE_NN_vs_original
  output$plot_NN_performance <- plot_NN_performance
  output$plot_PR_vs_NN <- plot_PR_vs_NN
  output$plot_taylor <- plot_taylor
  output$plot_history <- plot_history
  
  return(output)
}

```




# Example 1

```{r}

L <- 3
h_neurons_at_each_layer <- 32
af <- "tanh"
my_max_norm <- list("l2_norm", 1)

# q taylor with 1 at the end for regression
q_taylor_vector <- rep(q_taylor_at_each_layer,L)
q_taylor_vector <- c(q_taylor_vector,1)

# h neurons with 1 at the end for regression
h_neurons_vector <- rep(h_neurons_at_each_layer,L)
h_neurons_vector <- c(h_neurons_vector,1)


###### Create first the list with the af at each layer:
af_string_list <- vector(mode = "list", length = L+1)
for (i in 1:L){
  af_string_list[i] <- af
}
# Add linear at the end so we have regression setting.
af_string_list[L+1] <- "linear"



example1 <- perform_example_from_train_test(
          train = train,
          test = test,
          af_string_list = af_string_list,
          h_neurons_vector = h_neurons_vector,
          q_taylor_vector = q_taylor_vector,
          forced_max_Q = forced_max_Q,
          my_max_norm = my_max_norm,
          my_optimizer = my_optimizer,
          my_loss = my_loss,
          my_metrics = my_metrics,
          my_epochs = my_epochs,
          my_batch = my_batch,
          my_validation_split = my_validation_split,
          my_verbose
        )
```


```{r}
example1
```



Creating a better plot for the paper:

```{r}

plot.example <- cowplot::plot_grid(my_nn$plot_NN_performance, my_nn$plot_PR_vs_NN, labels = c("A", "B"), scale = 0.9, label_size = 10)

plot.example

plot.example2 <- cowplot::plot_grid(my_nn$plot_taylor[[1]], my_nn$plot_taylor[[2]], labels = c("Layer 1", "Layer 2"), scale = 0.8, label_size = 10, ncol = 1)

plot.example2

setEPS()
postscript("temporal/fig_performance_l1.eps", width = 6, height = 4)
plot.example
dev.off()

setEPS()
postscript("temporal/fig_taylor_layers_l1.eps", width = 6, height = 4)
plot.example2
dev.off()

```

